### PR TITLE
test: add tests for parameters and request bodies

### PR DESCRIPTION
**Pull request by mingwho**
### Description

Added tests for parameters and request bodies.
Also added pre-commit hook and prettier

### Type of change

- [x] This change adds new tests

### Checklist:

- [x] Self-review of my own code
- [x] Commented the code, particularly in hard-to-understand areas
- [x] Corresponding changes to the documentation
- [x] Ran test on local
- [x] Generated build on local

### CODE REVIEW

**Comment by tauqeernasir** [comment]
@mingwho Thank you Ming. Can we please add some more edge cases to the test suites?

cc @heypran @yogeshkathayat

**Comment by heypran** [comment]
> @mingwho Thank you Ming. Can we please add some more edge cases to the test suites?
> 
> cc @heypran @yogeshkathayat

@mingwho , we can write cases with improper syntax missing `{` , `,` or expression block names, passing falsy values like null, undefined,  -0 etc  or  Infinity etc. Let me know if you need any help.

**Comment by tauqeernasir** [comment]
> > @mingwho Thank you Ming. Can we please add some more edge cases to the test suites?
> > cc @heypran @yogeshkathayat
> 
> @mingwho , we can write cases with improper syntax missing `{` , `,` or expression block names, passing falsy values like null, undefined, -0 etc or Infinity etc. Let me know if you need any help.

@heypran Kindly add test cases yourself. It'd be easy for your in incorporate those :) Thank you.

**Comment by heypran** [comment]
> > > @mingwho Thank you Ming. Can we please add some more edge cases to the test suites?
> > > cc @heypran @yogeshkathayat
> > 
> > 
> > @mingwho , we can write cases with improper syntax missing `{` , `,` or expression block names, passing falsy values like null, undefined, -0 etc or Infinity etc. Let me know if you need any help.
> 
> @heypran Kindly add test cases yourself. It'd be easy for you to incorporate those :) Thank you.

Sure! will do

**Pull request merged**
